### ISSUE TITLE
opening big albums

### ISSUE THREAD

**Issue by ghost** [ruuk/plugin.image.picasa#2]
When we open big albums with 500-1000 pictures and we try to run slideshow. It take a lot of time to load, because we check MimeType of each file: "DEBUG: CCurlFile::GetMimeType". Is this really needed, can we switch it off somehow. I'm not sure if this is connected with plugin or Kodi.

**Comment by ruuk** [comment]
This is a Kodi issue. Also this add-on is no longer in development.

**Comment by ghost** [comment]
No it's not Kodi. You can speed it up.

                mimetype = ''
                for c in content:
                    if c['type'].startswith('video'):
                        mtype = 'video'
                        video = c['url']
                        mimetype = 'video/mp4'
                    elif c['type'].startswith('image'):
                        mtype = 'pictures'
                        img_url = c['url']
                        ext = img_url.split(".")[-1].lower()

                        if ext == 'jpg' or ext == 'jpeg':
                            mimetype = 'image/jpeg'
                        elif ext == 'gif':
                            mimetype = 'image/gif'

...

                items.append({	'label':title,
                                'path':mtype == 'video' and video or img_url,
                                'thumbnail':thumb,
                                'context_menu':contextMenu,
                                'properties': [('mimetype', mimetype)],
                                'info':{'type':mtype},
                                'is_playable':True
                })

**Comment by ruuk** [comment]
I guess if you can set the mimetype it makes sense you could prevent Kodi from doing the check. I've probably seen that you could set the mimetype in the docs in the past, just not at the same time I was wondering why the heck Kodi was checking the mimetype for every image before starting the slideshow (which still doesn't make sense to me even with this). Thanks, I've learned something new :smile:.
